### ISSUE TITLE
more wrapping option

### ISSUE THREAD

**Issue by jcolomb** [rstudio/visual-markdown-editing#11]
hello,

line wrapping does help a lot for text review. It would be nice to be able to wrap with multiple options

at sentences (`wrap: sentence`)
at a specific length (similar to `wrap: 80`)
( an additional option for wrapping at commas in the last 15 available characters would also be cool)

this does unfortunately not work:

```
editor_options:
  markdown:
    wrap:
      - sentence
      - 80
```
